font_size 13
background_opacity 0.7
window_padding_width 5

map ctrl+shift+equal change_font_size all +1.0
map ctrl+shift+minus change_font_size all -1.0

shell "/bin/fish"


# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME


# BEGIN_KITTY_FONTS
font_family      family="Maple Mono NF"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
